#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 
bspc config focus_follows_pointer         true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc config border_width        0
bspc config window_gap          15
bspc config single_monocle      false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a firefox desktop='^6' state=tiled follow=on focus=on
bspc rule -a emacs desktop='^2' follow=on focus=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

#tint2 
feh --bg-fill ~/wall/vaporwave.png
picom 
#~/minimal/launch.sh
#~/polybar/launch.sh
~/.config/polybar/launch.sh
#~/.config/openbox/polybar/nordic/launch.sh
