[theme]
name = "native"

[icons]
name = "awesome"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^10}"

[[block]]
block = "sound"
format = "{volume}"
on_click = "pavucontrol"
[block.mappings]
"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = "🔈"
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"

[[block]]
block = "cpu"
icons_format = "{icon} "

[[block]]
block = "battery"
interval = 10
format = " {percentage} {time}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used}/{total} ({available} free)"

[[block]]
block = "time"
format = "%a %d/%m %R"
timezone = "Asia/Kathmandu"
interval = 60
locale = "en_US"
